// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MainDelayReasonRateProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Main {

  /// <summary>Holder for reflection information generated from MainDelayReasonRateProto.proto</summary>
  public static partial class MainDelayReasonRateProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for MainDelayReasonRateProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MainDelayReasonRateProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5NYWluRGVsYXlSZWFzb25SYXRlUHJvdG8ucHJvdG8SBG1haW4iBwoFRW1w",
            "dHkizwIKE01haW5EZWxheVJlYXNvblJhdGUSDAoEWWVhchgBIAEoBRINCgVN",
            "b250aBgCIAEoBRIYChBOdW1DYXJyaWVyRGVsYXlzGAMgASgFEhgKEE51bVdl",
            "YXRoZXJEZWxheXMYBCABKAUSFAoMTnVtTkFTRGVsYXlzGAUgASgFEhkKEU51",
            "bVNlY3VyaXR5RGVsYXlzGAYgASgFEh0KFU51bUxhdGVBaXJjcmFmdERlbGF5",
            "cxgHIAEoBRITCgtUb3RhbERlbGF5cxgIIAEoBRIYChBDYXJyaWVyRGVsYXlS",
            "YXRlGAkgASgBEhgKEFdlYXRoZXJEZWxheVJhdGUYCiABKAESFAoMTkFTRGVs",
            "YXlSYXRlGAsgASgBEhkKEVNlY3VyaXR5RGVsYXlSYXRlGAwgASgBEh0KFUxh",
            "dGVBaXJjcmFmdERlbGF5UmF0ZRgNIAEoASJDChdNYWluRGVsYXlSZWFzb25S",
            "YXRlTGlzdBIoCgVpdGVtcxgBIAMoCzIZLm1haW4uTWFpbkRlbGF5UmVhc29u",
            "UmF0ZTJWCg1GbGlnaHRTZXJ2aWNlEkUKF0dldE1haW5EZWxheVJlYXNvblJh",
            "dGVzEgsubWFpbi5FbXB0eRodLm1haW4uTWFpbkRlbGF5UmVhc29uUmF0ZUxp",
            "c3RCD1oNLi9wcm90bztwcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Main.Empty), global::Main.Empty.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Main.MainDelayReasonRate), global::Main.MainDelayReasonRate.Parser, new[]{ "Year", "Month", "NumCarrierDelays", "NumWeatherDelays", "NumNASDelays", "NumSecurityDelays", "NumLateAircraftDelays", "TotalDelays", "CarrierDelayRate", "WeatherDelayRate", "NASDelayRate", "SecurityDelayRate", "LateAircraftDelayRate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Main.MainDelayReasonRateList), global::Main.MainDelayReasonRateList.Parser, new[]{ "Items" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Empty : pb::IMessage<Empty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Main.MainDelayReasonRateProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty(Empty other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MainDelayReasonRate : pb::IMessage<MainDelayReasonRate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MainDelayReasonRate> _parser = new pb::MessageParser<MainDelayReasonRate>(() => new MainDelayReasonRate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MainDelayReasonRate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Main.MainDelayReasonRateProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainDelayReasonRate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainDelayReasonRate(MainDelayReasonRate other) : this() {
      year_ = other.year_;
      month_ = other.month_;
      numCarrierDelays_ = other.numCarrierDelays_;
      numWeatherDelays_ = other.numWeatherDelays_;
      numNASDelays_ = other.numNASDelays_;
      numSecurityDelays_ = other.numSecurityDelays_;
      numLateAircraftDelays_ = other.numLateAircraftDelays_;
      totalDelays_ = other.totalDelays_;
      carrierDelayRate_ = other.carrierDelayRate_;
      weatherDelayRate_ = other.weatherDelayRate_;
      nASDelayRate_ = other.nASDelayRate_;
      securityDelayRate_ = other.securityDelayRate_;
      lateAircraftDelayRate_ = other.lateAircraftDelayRate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainDelayReasonRate Clone() {
      return new MainDelayReasonRate(this);
    }

    /// <summary>Field number for the "Year" field.</summary>
    public const int YearFieldNumber = 1;
    private int year_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Year {
      get { return year_; }
      set {
        year_ = value;
      }
    }

    /// <summary>Field number for the "Month" field.</summary>
    public const int MonthFieldNumber = 2;
    private int month_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Month {
      get { return month_; }
      set {
        month_ = value;
      }
    }

    /// <summary>Field number for the "NumCarrierDelays" field.</summary>
    public const int NumCarrierDelaysFieldNumber = 3;
    private int numCarrierDelays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumCarrierDelays {
      get { return numCarrierDelays_; }
      set {
        numCarrierDelays_ = value;
      }
    }

    /// <summary>Field number for the "NumWeatherDelays" field.</summary>
    public const int NumWeatherDelaysFieldNumber = 4;
    private int numWeatherDelays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumWeatherDelays {
      get { return numWeatherDelays_; }
      set {
        numWeatherDelays_ = value;
      }
    }

    /// <summary>Field number for the "NumNASDelays" field.</summary>
    public const int NumNASDelaysFieldNumber = 5;
    private int numNASDelays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumNASDelays {
      get { return numNASDelays_; }
      set {
        numNASDelays_ = value;
      }
    }

    /// <summary>Field number for the "NumSecurityDelays" field.</summary>
    public const int NumSecurityDelaysFieldNumber = 6;
    private int numSecurityDelays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumSecurityDelays {
      get { return numSecurityDelays_; }
      set {
        numSecurityDelays_ = value;
      }
    }

    /// <summary>Field number for the "NumLateAircraftDelays" field.</summary>
    public const int NumLateAircraftDelaysFieldNumber = 7;
    private int numLateAircraftDelays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumLateAircraftDelays {
      get { return numLateAircraftDelays_; }
      set {
        numLateAircraftDelays_ = value;
      }
    }

    /// <summary>Field number for the "TotalDelays" field.</summary>
    public const int TotalDelaysFieldNumber = 8;
    private int totalDelays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalDelays {
      get { return totalDelays_; }
      set {
        totalDelays_ = value;
      }
    }

    /// <summary>Field number for the "CarrierDelayRate" field.</summary>
    public const int CarrierDelayRateFieldNumber = 9;
    private double carrierDelayRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double CarrierDelayRate {
      get { return carrierDelayRate_; }
      set {
        carrierDelayRate_ = value;
      }
    }

    /// <summary>Field number for the "WeatherDelayRate" field.</summary>
    public const int WeatherDelayRateFieldNumber = 10;
    private double weatherDelayRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double WeatherDelayRate {
      get { return weatherDelayRate_; }
      set {
        weatherDelayRate_ = value;
      }
    }

    /// <summary>Field number for the "NASDelayRate" field.</summary>
    public const int NASDelayRateFieldNumber = 11;
    private double nASDelayRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double NASDelayRate {
      get { return nASDelayRate_; }
      set {
        nASDelayRate_ = value;
      }
    }

    /// <summary>Field number for the "SecurityDelayRate" field.</summary>
    public const int SecurityDelayRateFieldNumber = 12;
    private double securityDelayRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SecurityDelayRate {
      get { return securityDelayRate_; }
      set {
        securityDelayRate_ = value;
      }
    }

    /// <summary>Field number for the "LateAircraftDelayRate" field.</summary>
    public const int LateAircraftDelayRateFieldNumber = 13;
    private double lateAircraftDelayRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LateAircraftDelayRate {
      get { return lateAircraftDelayRate_; }
      set {
        lateAircraftDelayRate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MainDelayReasonRate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MainDelayReasonRate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Year != other.Year) return false;
      if (Month != other.Month) return false;
      if (NumCarrierDelays != other.NumCarrierDelays) return false;
      if (NumWeatherDelays != other.NumWeatherDelays) return false;
      if (NumNASDelays != other.NumNASDelays) return false;
      if (NumSecurityDelays != other.NumSecurityDelays) return false;
      if (NumLateAircraftDelays != other.NumLateAircraftDelays) return false;
      if (TotalDelays != other.TotalDelays) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CarrierDelayRate, other.CarrierDelayRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(WeatherDelayRate, other.WeatherDelayRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(NASDelayRate, other.NASDelayRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SecurityDelayRate, other.SecurityDelayRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LateAircraftDelayRate, other.LateAircraftDelayRate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Year != 0) hash ^= Year.GetHashCode();
      if (Month != 0) hash ^= Month.GetHashCode();
      if (NumCarrierDelays != 0) hash ^= NumCarrierDelays.GetHashCode();
      if (NumWeatherDelays != 0) hash ^= NumWeatherDelays.GetHashCode();
      if (NumNASDelays != 0) hash ^= NumNASDelays.GetHashCode();
      if (NumSecurityDelays != 0) hash ^= NumSecurityDelays.GetHashCode();
      if (NumLateAircraftDelays != 0) hash ^= NumLateAircraftDelays.GetHashCode();
      if (TotalDelays != 0) hash ^= TotalDelays.GetHashCode();
      if (CarrierDelayRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CarrierDelayRate);
      if (WeatherDelayRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(WeatherDelayRate);
      if (NASDelayRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(NASDelayRate);
      if (SecurityDelayRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SecurityDelayRate);
      if (LateAircraftDelayRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LateAircraftDelayRate);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Year != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Year);
      }
      if (Month != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Month);
      }
      if (NumCarrierDelays != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumCarrierDelays);
      }
      if (NumWeatherDelays != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumWeatherDelays);
      }
      if (NumNASDelays != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NumNASDelays);
      }
      if (NumSecurityDelays != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NumSecurityDelays);
      }
      if (NumLateAircraftDelays != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(NumLateAircraftDelays);
      }
      if (TotalDelays != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(TotalDelays);
      }
      if (CarrierDelayRate != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(CarrierDelayRate);
      }
      if (WeatherDelayRate != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(WeatherDelayRate);
      }
      if (NASDelayRate != 0D) {
        output.WriteRawTag(89);
        output.WriteDouble(NASDelayRate);
      }
      if (SecurityDelayRate != 0D) {
        output.WriteRawTag(97);
        output.WriteDouble(SecurityDelayRate);
      }
      if (LateAircraftDelayRate != 0D) {
        output.WriteRawTag(105);
        output.WriteDouble(LateAircraftDelayRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Year != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Year);
      }
      if (Month != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Month);
      }
      if (NumCarrierDelays != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumCarrierDelays);
      }
      if (NumWeatherDelays != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumWeatherDelays);
      }
      if (NumNASDelays != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NumNASDelays);
      }
      if (NumSecurityDelays != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NumSecurityDelays);
      }
      if (NumLateAircraftDelays != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(NumLateAircraftDelays);
      }
      if (TotalDelays != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(TotalDelays);
      }
      if (CarrierDelayRate != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(CarrierDelayRate);
      }
      if (WeatherDelayRate != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(WeatherDelayRate);
      }
      if (NASDelayRate != 0D) {
        output.WriteRawTag(89);
        output.WriteDouble(NASDelayRate);
      }
      if (SecurityDelayRate != 0D) {
        output.WriteRawTag(97);
        output.WriteDouble(SecurityDelayRate);
      }
      if (LateAircraftDelayRate != 0D) {
        output.WriteRawTag(105);
        output.WriteDouble(LateAircraftDelayRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Year != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Year);
      }
      if (Month != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Month);
      }
      if (NumCarrierDelays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumCarrierDelays);
      }
      if (NumWeatherDelays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumWeatherDelays);
      }
      if (NumNASDelays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumNASDelays);
      }
      if (NumSecurityDelays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumSecurityDelays);
      }
      if (NumLateAircraftDelays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumLateAircraftDelays);
      }
      if (TotalDelays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalDelays);
      }
      if (CarrierDelayRate != 0D) {
        size += 1 + 8;
      }
      if (WeatherDelayRate != 0D) {
        size += 1 + 8;
      }
      if (NASDelayRate != 0D) {
        size += 1 + 8;
      }
      if (SecurityDelayRate != 0D) {
        size += 1 + 8;
      }
      if (LateAircraftDelayRate != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MainDelayReasonRate other) {
      if (other == null) {
        return;
      }
      if (other.Year != 0) {
        Year = other.Year;
      }
      if (other.Month != 0) {
        Month = other.Month;
      }
      if (other.NumCarrierDelays != 0) {
        NumCarrierDelays = other.NumCarrierDelays;
      }
      if (other.NumWeatherDelays != 0) {
        NumWeatherDelays = other.NumWeatherDelays;
      }
      if (other.NumNASDelays != 0) {
        NumNASDelays = other.NumNASDelays;
      }
      if (other.NumSecurityDelays != 0) {
        NumSecurityDelays = other.NumSecurityDelays;
      }
      if (other.NumLateAircraftDelays != 0) {
        NumLateAircraftDelays = other.NumLateAircraftDelays;
      }
      if (other.TotalDelays != 0) {
        TotalDelays = other.TotalDelays;
      }
      if (other.CarrierDelayRate != 0D) {
        CarrierDelayRate = other.CarrierDelayRate;
      }
      if (other.WeatherDelayRate != 0D) {
        WeatherDelayRate = other.WeatherDelayRate;
      }
      if (other.NASDelayRate != 0D) {
        NASDelayRate = other.NASDelayRate;
      }
      if (other.SecurityDelayRate != 0D) {
        SecurityDelayRate = other.SecurityDelayRate;
      }
      if (other.LateAircraftDelayRate != 0D) {
        LateAircraftDelayRate = other.LateAircraftDelayRate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Year = input.ReadInt32();
            break;
          }
          case 16: {
            Month = input.ReadInt32();
            break;
          }
          case 24: {
            NumCarrierDelays = input.ReadInt32();
            break;
          }
          case 32: {
            NumWeatherDelays = input.ReadInt32();
            break;
          }
          case 40: {
            NumNASDelays = input.ReadInt32();
            break;
          }
          case 48: {
            NumSecurityDelays = input.ReadInt32();
            break;
          }
          case 56: {
            NumLateAircraftDelays = input.ReadInt32();
            break;
          }
          case 64: {
            TotalDelays = input.ReadInt32();
            break;
          }
          case 73: {
            CarrierDelayRate = input.ReadDouble();
            break;
          }
          case 81: {
            WeatherDelayRate = input.ReadDouble();
            break;
          }
          case 89: {
            NASDelayRate = input.ReadDouble();
            break;
          }
          case 97: {
            SecurityDelayRate = input.ReadDouble();
            break;
          }
          case 105: {
            LateAircraftDelayRate = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Year = input.ReadInt32();
            break;
          }
          case 16: {
            Month = input.ReadInt32();
            break;
          }
          case 24: {
            NumCarrierDelays = input.ReadInt32();
            break;
          }
          case 32: {
            NumWeatherDelays = input.ReadInt32();
            break;
          }
          case 40: {
            NumNASDelays = input.ReadInt32();
            break;
          }
          case 48: {
            NumSecurityDelays = input.ReadInt32();
            break;
          }
          case 56: {
            NumLateAircraftDelays = input.ReadInt32();
            break;
          }
          case 64: {
            TotalDelays = input.ReadInt32();
            break;
          }
          case 73: {
            CarrierDelayRate = input.ReadDouble();
            break;
          }
          case 81: {
            WeatherDelayRate = input.ReadDouble();
            break;
          }
          case 89: {
            NASDelayRate = input.ReadDouble();
            break;
          }
          case 97: {
            SecurityDelayRate = input.ReadDouble();
            break;
          }
          case 105: {
            LateAircraftDelayRate = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MainDelayReasonRateList : pb::IMessage<MainDelayReasonRateList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MainDelayReasonRateList> _parser = new pb::MessageParser<MainDelayReasonRateList>(() => new MainDelayReasonRateList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MainDelayReasonRateList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Main.MainDelayReasonRateProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainDelayReasonRateList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainDelayReasonRateList(MainDelayReasonRateList other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MainDelayReasonRateList Clone() {
      return new MainDelayReasonRateList(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Main.MainDelayReasonRate> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Main.MainDelayReasonRate.Parser);
    private readonly pbc::RepeatedField<global::Main.MainDelayReasonRate> items_ = new pbc::RepeatedField<global::Main.MainDelayReasonRate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Main.MainDelayReasonRate> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MainDelayReasonRateList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MainDelayReasonRateList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MainDelayReasonRateList other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
