// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: MainDelayReasonRateProto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_MainDelayReasonRateProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_MainDelayReasonRateProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_MainDelayReasonRateProto_proto_rawDescGZIP(), []int{0}
}

type MainDelayReasonRate struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Year                  int32                  `protobuf:"varint,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Month                 int32                  `protobuf:"varint,2,opt,name=Month,proto3" json:"Month,omitempty"`
	NumCarrierDelays      int32                  `protobuf:"varint,3,opt,name=NumCarrierDelays,proto3" json:"NumCarrierDelays,omitempty"`
	NumWeatherDelays      int32                  `protobuf:"varint,4,opt,name=NumWeatherDelays,proto3" json:"NumWeatherDelays,omitempty"`
	NumNASDelays          int32                  `protobuf:"varint,5,opt,name=NumNASDelays,proto3" json:"NumNASDelays,omitempty"`
	NumSecurityDelays     int32                  `protobuf:"varint,6,opt,name=NumSecurityDelays,proto3" json:"NumSecurityDelays,omitempty"`
	NumLateAircraftDelays int32                  `protobuf:"varint,7,opt,name=NumLateAircraftDelays,proto3" json:"NumLateAircraftDelays,omitempty"`
	TotalDelays           int32                  `protobuf:"varint,8,opt,name=TotalDelays,proto3" json:"TotalDelays,omitempty"`
	CarrierDelayRate      float64                `protobuf:"fixed64,9,opt,name=CarrierDelayRate,proto3" json:"CarrierDelayRate,omitempty"`
	WeatherDelayRate      float64                `protobuf:"fixed64,10,opt,name=WeatherDelayRate,proto3" json:"WeatherDelayRate,omitempty"`
	NASDelayRate          float64                `protobuf:"fixed64,11,opt,name=NASDelayRate,proto3" json:"NASDelayRate,omitempty"`
	SecurityDelayRate     float64                `protobuf:"fixed64,12,opt,name=SecurityDelayRate,proto3" json:"SecurityDelayRate,omitempty"`
	LateAircraftDelayRate float64                `protobuf:"fixed64,13,opt,name=LateAircraftDelayRate,proto3" json:"LateAircraftDelayRate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MainDelayReasonRate) Reset() {
	*x = MainDelayReasonRate{}
	mi := &file_MainDelayReasonRateProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MainDelayReasonRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainDelayReasonRate) ProtoMessage() {}

func (x *MainDelayReasonRate) ProtoReflect() protoreflect.Message {
	mi := &file_MainDelayReasonRateProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainDelayReasonRate.ProtoReflect.Descriptor instead.
func (*MainDelayReasonRate) Descriptor() ([]byte, []int) {
	return file_MainDelayReasonRateProto_proto_rawDescGZIP(), []int{1}
}

func (x *MainDelayReasonRate) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MainDelayReasonRate) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *MainDelayReasonRate) GetNumCarrierDelays() int32 {
	if x != nil {
		return x.NumCarrierDelays
	}
	return 0
}

func (x *MainDelayReasonRate) GetNumWeatherDelays() int32 {
	if x != nil {
		return x.NumWeatherDelays
	}
	return 0
}

func (x *MainDelayReasonRate) GetNumNASDelays() int32 {
	if x != nil {
		return x.NumNASDelays
	}
	return 0
}

func (x *MainDelayReasonRate) GetNumSecurityDelays() int32 {
	if x != nil {
		return x.NumSecurityDelays
	}
	return 0
}

func (x *MainDelayReasonRate) GetNumLateAircraftDelays() int32 {
	if x != nil {
		return x.NumLateAircraftDelays
	}
	return 0
}

func (x *MainDelayReasonRate) GetTotalDelays() int32 {
	if x != nil {
		return x.TotalDelays
	}
	return 0
}

func (x *MainDelayReasonRate) GetCarrierDelayRate() float64 {
	if x != nil {
		return x.CarrierDelayRate
	}
	return 0
}

func (x *MainDelayReasonRate) GetWeatherDelayRate() float64 {
	if x != nil {
		return x.WeatherDelayRate
	}
	return 0
}

func (x *MainDelayReasonRate) GetNASDelayRate() float64 {
	if x != nil {
		return x.NASDelayRate
	}
	return 0
}

func (x *MainDelayReasonRate) GetSecurityDelayRate() float64 {
	if x != nil {
		return x.SecurityDelayRate
	}
	return 0
}

func (x *MainDelayReasonRate) GetLateAircraftDelayRate() float64 {
	if x != nil {
		return x.LateAircraftDelayRate
	}
	return 0
}

type MainDelayReasonRateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MainDelayReasonRate `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MainDelayReasonRateList) Reset() {
	*x = MainDelayReasonRateList{}
	mi := &file_MainDelayReasonRateProto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MainDelayReasonRateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainDelayReasonRateList) ProtoMessage() {}

func (x *MainDelayReasonRateList) ProtoReflect() protoreflect.Message {
	mi := &file_MainDelayReasonRateProto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainDelayReasonRateList.ProtoReflect.Descriptor instead.
func (*MainDelayReasonRateList) Descriptor() ([]byte, []int) {
	return file_MainDelayReasonRateProto_proto_rawDescGZIP(), []int{2}
}

func (x *MainDelayReasonRateList) GetItems() []*MainDelayReasonRate {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_MainDelayReasonRateProto_proto protoreflect.FileDescriptor

const file_MainDelayReasonRateProto_proto_rawDesc = "" +
	"\n" +
	"\x1eMainDelayReasonRateProto.proto\x12\x04main\"\a\n" +
	"\x05Empty\"\xa1\x04\n" +
	"\x13MainDelayReasonRate\x12\x12\n" +
	"\x04Year\x18\x01 \x01(\x05R\x04Year\x12\x14\n" +
	"\x05Month\x18\x02 \x01(\x05R\x05Month\x12*\n" +
	"\x10NumCarrierDelays\x18\x03 \x01(\x05R\x10NumCarrierDelays\x12*\n" +
	"\x10NumWeatherDelays\x18\x04 \x01(\x05R\x10NumWeatherDelays\x12\"\n" +
	"\fNumNASDelays\x18\x05 \x01(\x05R\fNumNASDelays\x12,\n" +
	"\x11NumSecurityDelays\x18\x06 \x01(\x05R\x11NumSecurityDelays\x124\n" +
	"\x15NumLateAircraftDelays\x18\a \x01(\x05R\x15NumLateAircraftDelays\x12 \n" +
	"\vTotalDelays\x18\b \x01(\x05R\vTotalDelays\x12*\n" +
	"\x10CarrierDelayRate\x18\t \x01(\x01R\x10CarrierDelayRate\x12*\n" +
	"\x10WeatherDelayRate\x18\n" +
	" \x01(\x01R\x10WeatherDelayRate\x12\"\n" +
	"\fNASDelayRate\x18\v \x01(\x01R\fNASDelayRate\x12,\n" +
	"\x11SecurityDelayRate\x18\f \x01(\x01R\x11SecurityDelayRate\x124\n" +
	"\x15LateAircraftDelayRate\x18\r \x01(\x01R\x15LateAircraftDelayRate\"J\n" +
	"\x17MainDelayReasonRateList\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.main.MainDelayReasonRateR\x05items2V\n" +
	"\rFlightService\x12E\n" +
	"\x17GetMainDelayReasonRates\x12\v.main.Empty\x1a\x1d.main.MainDelayReasonRateListB\x0fZ\r./proto;protob\x06proto3"

var (
	file_MainDelayReasonRateProto_proto_rawDescOnce sync.Once
	file_MainDelayReasonRateProto_proto_rawDescData []byte
)

func file_MainDelayReasonRateProto_proto_rawDescGZIP() []byte {
	file_MainDelayReasonRateProto_proto_rawDescOnce.Do(func() {
		file_MainDelayReasonRateProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MainDelayReasonRateProto_proto_rawDesc), len(file_MainDelayReasonRateProto_proto_rawDesc)))
	})
	return file_MainDelayReasonRateProto_proto_rawDescData
}

var file_MainDelayReasonRateProto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_MainDelayReasonRateProto_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: main.Empty
	(*MainDelayReasonRate)(nil),     // 1: main.MainDelayReasonRate
	(*MainDelayReasonRateList)(nil), // 2: main.MainDelayReasonRateList
}
var file_MainDelayReasonRateProto_proto_depIdxs = []int32{
	1, // 0: main.MainDelayReasonRateList.items:type_name -> main.MainDelayReasonRate
	0, // 1: main.FlightService.GetMainDelayReasonRates:input_type -> main.Empty
	2, // 2: main.FlightService.GetMainDelayReasonRates:output_type -> main.MainDelayReasonRateList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_MainDelayReasonRateProto_proto_init() }
func file_MainDelayReasonRateProto_proto_init() {
	if File_MainDelayReasonRateProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MainDelayReasonRateProto_proto_rawDesc), len(file_MainDelayReasonRateProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MainDelayReasonRateProto_proto_goTypes,
		DependencyIndexes: file_MainDelayReasonRateProto_proto_depIdxs,
		MessageInfos:      file_MainDelayReasonRateProto_proto_msgTypes,
	}.Build()
	File_MainDelayReasonRateProto_proto = out.File
	file_MainDelayReasonRateProto_proto_goTypes = nil
	file_MainDelayReasonRateProto_proto_depIdxs = nil
}
